### PR TITLE
Merge development into main

### PR DESCRIPTION
**Pull request by jamiewilbraham**

### CODE REVIEW

**Comment by rinisbet** [comment]
Hey Jamie, found these bugs. Can we get them fixed before we merge?

[[Development] Deleted models indicator is incorrect · Issue #137 · Azure-Samples/digital-twins-explorer (github.com)](https://github.com/Azure-Samples/digital-twins-explorer/issues/137)

[Model shows as deleted even after re-uploaded · Issue #134 · Azure-Samples/digital-twins-explorer (github.com)](https://github.com/Azure-Samples/digital-twins-explorer/issues/134)

**Comment by jamiewilbraham** [comment]
hi @rinisbet,

Yes, no problem. We are currently addressing those issues along with others that have been raised. Will push to development ASAP.

-Jamie

**Comment by rinisbet** [comment]
Incredible, thank you Jamie!

**Comment by jamiewilbraham** [comment]
@rinisbet - have updated development with fixes.

**Pull request merged**
